# Generated by Django 5.2.8 on 2026-05-10 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disciplina_professor_avaliacao_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='dia_semana',
            field=models.CharField(choices=[('2', 'Segunda'), ('3', 'Terça'), ('4', 'Quarta'), ('5', 'Quinta'), ('6', 'Sexta')], default='2', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario_fim',
            field=models.TimeField(default='07:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario_inicio',
            field=models.TimeField(default='07:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.professor'),
            preserve_default=False,
        ),
    ]
