# Generated by Django 5.2.8 on 2026-05-10 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_disciplina_options_disciplina_dia_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horario_inicio',
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('2', 'Segunda'), ('3', 'Terça'), ('4', 'Quarta'), ('5', 'Quinta'), ('6', 'Sexta')], max_length=1)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.disciplina')),
            ],
        ),
    ]
