# Generated by Django 5.2.8 on 2026-05-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_disciplina_dia_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='quantidade_turmas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
