# Generated by Django 5.2.8 on 2026-05-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_disciplina_quantidade_turmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_disciplina', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'ordering': ['-ano', '-semestre'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(choices=[('07-09', '07:00 - 09:00'), ('09-11', '09:00 - 11:00'), ('11-13', '11:00 - 13:00'), ('13-15', '13:00 - 15:00'), ('15-17', '15:00 - 17:00'), ('17-19', '17:00 - 19:00'), ('19-21', '19:00 - 21:00')], max_length=5)),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_disciplina', to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_professor', to='core.professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
