# Generated by Django 5.2.8 on 2026-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_horario_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('Sob avaliaçao', 'Sob Avaliacao')], default='Sob avaliaçao', max_length=20),
        ),
    ]
