# Generated by Django 5.2.8 on 2026-06-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_avaliacao_professor_alter_avaliacao_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_denuncia', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='core.avaliacao')),
            ],
        ),
    ]
