# Generated by Django 5.2.8 on 2026-06-01 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_denuncia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota_disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota_prof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
