# Generated by Django 5.2.8 on 2026-06-11 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_professor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRE', 'Pré-requisito'), ('CO', 'Co-requisito')], max_length=3)),
                ('operador', models.CharField(choices=[('AND', 'E'), ('OR', 'OU')], default='AND', max_length=3)),
                ('disciplina_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_requisitos', to='core.disciplina')),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='compoem_grupos', to='core.disciplina')),
            ],
        ),
    ]
