# Generated by Django 5.2.8 on 2026-06-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_disciplina_ementa_requisito"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaSemanaAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("SEG", "Segunda-feira"),
                            ("TER", "Terça-feira"),
                            ("QUA", "Quarta-feira"),
                            ("QUI", "Quinta-feira"),
                            ("SEX", "Sexta-feira"),
                            ("SAB", "Sábado"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia da Semana",
                "verbose_name_plural": "Dias da Semana",
                "ordering": ["dia"],
            },
        ),
        migrations.RemoveField(
            model_name="denuncia",
            name="data_denuncia",
        ),
        migrations.AddField(
            model_name="turma",
            name="dias_semana",
            field=models.ManyToManyField(
                blank=True, related_name="turmas", to="core.DiaSemanaAula"
            ),
        ),
    ]
