# Generated by Django 5.2.8 on 2026-06-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_diasemanaaula_remove_denuncia_data_denuncia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('disciplina', 'professor', 'horario')},
        ),
    ]
