# Generated by Django 5.2.8 on 2026-06-16 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_turma_dia_semana"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="turma",
            unique_together={("disciplina", "professor", "horario")},
        ),
    ]
