# Generated by Django 5.2.8 on 2026-06-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_solicitacaodisciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('cursando', 'Cursando'), ('concluido', 'Concluido'), ('trancado', 'Trancado')], default='cursando', max_length=10),
        ),
    ]
