# Generated by Django 5.2.8 on 2026-06-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_matricula_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('total_creditos_obrigatorios', models.PositiveIntegerField(default=0)),
                ('total_creditos_optativos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='curriculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='core.curriculo'),
        ),
        migrations.CreateModel(
            name='CurriculoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativa', 'Optativa')], max_length=15)),
                ('periodo_recomendado', models.PositiveIntegerField()),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.curriculo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculo_items', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Item de Currículo',
                'verbose_name_plural': 'Itens de Currículo',
                'ordering': ['periodo_recomendado', 'tipo', 'disciplina__nome'],
                'unique_together': {('curriculo', 'disciplina')},
            },
        ),
    ]
