# Generated by Django 6.0.6 on 2026-07-01 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_denuncia_data_denuncia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('data_denuncia', models.DateTimeField(auto_now_add=True)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_disciplina', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_disciplina', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Denúncia de Disciplina',
                'verbose_name_plural': 'Denúncias de Disciplinas',
                'ordering': ['-data_denuncia'],
            },
        ),
    ]
